name: Rust

on: 
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        target: wasm32-unknown-unknown

    - name: Build
      run: cargo build --verbose

    - name: Install Trunk
      run: cargo install trunk

    # Build demos.

    - name: Build Demo Web
      run: env -C demo_web trunk build

    - name: Build Demo Native
      run: env -C demo_native cargo build --verbose

    # Tests and lints.

    - name: Run tests
      run: cargo test --verbose

    - name: Check rust formatting
      run:  cargo fmt --all --check

    - name: Clippy
      run:  cargo clippy --all-features -- -D warnings 

    - name: Documentation
      run:  cargo doc

    # Build the Android demo.

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Cargo NDK
      run: cargo install cargo-ndk

    - name: Install Rust Android Target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android

    - name: Build APK
      working-directory: ./demo_android
      run: make apk
